$CMD_CR_s = Struct.new(:cmd, :rm_type, :pc, :names, :timeout) 
$CMD_GR_s = Struct.new(:cmd, :rid)
$CMD_RV_s = Struct.new(:cmd, :rid, :token, :vote)

class COMMAND
	CREATE_ROOM = "cr"
	GET_RESULTS = "gr"
	REGISTER_VOTE = "rv"
end

class ERR
	OK = "ERR100"
	
	BAD_PARAM_COUNT = "ERR101"
	BAD_ROOM_ID = "ERR102"
	BAD_ROOM_ID_LEN = "ERR103"
	BAD_ROOM_TYPE = "ERR104"
	BAD_TIMEOUT_FORMAT = "ERR105"
	BAD_TIMEOUT_INTERVAL = "ERR106"
	BAD_TOKEN = "ERR107"
	BAD_TOKEN_LEN = "ERR108"
	BAD_VOTE_VALUE = "ERR109"
	MAX_ROOM_COUNT_REACHED = "ERR110"
	NOT_ENOUGH_PARTICIPANTS = "ERR111"
	ROOM_INACTIVE = "ERR112"
	ROOM_STILL_ACTIVE = "ERR113"
	UNKNOW_COMMAND = "ERR114"
	UNKNOW_FIELD = "ERR115"
end

class VROOM
	PUB_VOTING = "pu"
	PRIV_VOTING = "pr"

	MIN_TIMEOUT = 10
	MAX_TIMEOUT = 999

	ROOM_ID_LEN = 20
	TOKEN_LEN = 10

	OLD_OFFSET = 20

	MAX_ROOM_COUNT = 20
end
